language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - '2.7'
  - '3.4'
  - '3.5'

install:
  - sudo apt-get update

  # Install Miniconda.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda.
  - conda info -a

  # Create conda environment and install matplotlib dependency
  # (as this can't be installed outside of conda on OSX).
  - "conda create -q -n test -c bioconda -c r -c defaults -c conda-forge
    python=$TRAVIS_PYTHON_VERSION matplotlib"

  # Activate environment and install IM-Fusion.
  - source activate test
  - pip install .[dev]

before_script:
  # Use xvfb during testing for matplotlib.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    py.test --cov imfusion --cov-report term-missing

after_success:
    - coveralls
