language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

install:
  # Update pip and setup tools.
  - pip install --upgrade pip
  - pip install --upgrade setuptools

  # Install IM-Fusion with development dependencies.
  - pip install .[dev]

before_script:
  # Use xvfb during testing for matplotlib.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    py.test --cov imfusion --cov-report term-missing

after_success:
    - coveralls
