name: imfusion-dev
dependencies:
  - python = 2.7

  - future
  - toolz

  - pandas
  - numexpr
  - scipy
  - seaborn

  # Testing/development dependencies.
  - sphinx
  - pytest

  - pip:
    - pysam == 0.8.4
    - git+https://github.com/mdshw5/pyfaidx.git
    - intervaltree

    # Optional dependencies
    # - rpy2    # For single-sample test.

    # Testing/development dependencies.
    - sphinx-autobuild
    - pytest-mock
    - pytest-datafiles
    - pytest-coverage
    - pytest-helpers-namespace
