name: imfusion-dev
channels:
  - jrderuiter
  - bioconda
  - r
dependencies:
  - python

  # Basic dependencies.
  - intervaltree
  - future
  - pandas
  - numexpr
  - pysam ==0.8.4
  - toolz
  - scipy
  - seaborn
  - pyfaidx
  - intervaltree
  - pathlib2 # [py27]
  - r
  - rpy2

  # Bioconda dependencies.
  - tophat
  - bowtie
  - subread

  # Test dependencies.
  - mock
  - pytest
  - pytest-datafiles
  - pytest-mock
  - pytest-helpers-namespace
