name: imfusion-dev-py27
channels:
    - conda-forge
    - defaults
    - r
    - bioconda
dependencies:
    # Python dependencies.
    - python =2.7.*
    - future =0.16
    - intervaltree
    - pandas =0.19.2
    - numexpr
    - pysam >=0.8.4
    - toolz
    - scipy
    - seaborn
    - pyfaidx
    - intervaltree
    - pathlib2 # [py27]
    - typing # [py27]
    - r =3.3.1
    - rpy2 >=2.7.4

    # External dependencies.
    - star
    - subread
    - stringtie

    # Development dependencies.
    - sphinx
    - pytest
    - pytest-mock
    - pytest-cov
    - pylint

    - yapf
    - pytest-datafiles
    - pytest-helpers-namespace
