name: imfusion-dev
channels:
    - r
    - bioconda
    - jrderuiter
dependencies:
    # Python dependencies.
    - python =3.5.2
    - future =0.16
    - intervaltree
    - frozendict
    - pandas =0.19.2
    - numexpr
    - pysam >=0.8.4
    - toolz
    - scipy
    - seaborn
    - pyfaidx
    - intervaltree
    - pathlib2 # [py27]
    - r =3.3.1
    - rpy2 >=2.7.4

    # External dependencies.
    - star
    - subread
    - stringtie

    # Development dependencies.
    - sphinx
    - pytest
    - pytest-mock
    - pytest-datafiles
    - pytest-cov
    - pytest-helpers-namespace
    - pylint
    - yapf
