package:
  name: imfusion
  version: 0.2.0.dev0

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - setuptools

    # Python dependencies.
    - python
    - future
    - frozendict
    - pandas
    - numexpr
    - pysam >=0.8.4
    - toolz
    - scipy
    - seaborn
    - pyfaidx
    - intervaltree
    - pathlib2 # [py27]
    - r
    - rpy2 >=2.7.4

  run:
    # Python dependencies.
    - python
    - intervaltree
    - future
    - frozendict
    - pandas
    - numexpr
    - pysam >=0.8.4
    - toolz
    - scipy
    - seaborn
    - pyfaidx
    - intervaltree
    - pathlib2 # [py27]
    - r
    - rpy2 >=2.7.4

    # External dependencies.
    - star
    - subread
    - stringtie

test:
  imports:
    - imfusion

  commands:
    - imfusion-build -h
    - STAR --version
    - featureCounts -v
    # - py.test $SRC_DIR

  requires:
    - mock
    - pytest
    - pytest-datafiles
    - pytest-mock
    - pytest-helpers-namespace

about:
  home: https://github.com/jrderuiter/im-fusion
  license: MIT
  summary: "IM-Fusion - Tool for identifying transposon insertions
    and their effects from RNA-sequencing data"
