package:
  name: imfusion
  version: 0.2.0

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - setuptools

    # Python dependencies.
    - python
    - future
    - pandas
    - numexpr
    - pysam >=0.9.1
    - toolz
    - scipy
    - seaborn
    - pyfaidx >=0.4.8.1
    - intervaltree
    - pathlib2 # [py27]
    - typing # [py27]
    - r
    - rpy2 >=2.7.4
    - htslib <1.4

  run:
    # Python dependencies.
    - python
    - intervaltree
    - future
    - pandas
    - numexpr
    - pysam >=0.9.1
    - toolz
    - scipy
    - seaborn
    - pyfaidx >=0.4.8.1
    - intervaltree
    - pathlib2 # [py27]
    - typing # [py27]
    - r
    - rpy2 >=2.7.4
    - htslib <1.4

    # External dependencies.
    - star
    - subread
    - stringtie
    - tophat2 # [py27]
    - bowtie # [py27]

test:
  imports:
    - imfusion

  commands:
    - imfusion-build -h
    - imfusion-insertions -h
    - imfusion-expression -h
    - imfusion-merge -h
    - imfusion-ctg -h
    - STAR --version
    - featureCounts -v

about:
  home: https://github.com/jrderuiter/im-fusion
  license: MIT
  summary: "IM-Fusion - Tool for identifying transposon insertions
    and their effects from RNA-sequencing data"
